"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastifyNotifications from "./components/ToastifyNotifications";
import { AuthProvider } from "./Provider";
import Providers from "./Providers";
import { usePathname } from "next/navigation";
import { Redux } from "./redux/providers";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();
  return (
    <>
      {pathName == "/template1" ? (
        <html lang="en" className="temp1-html">
        <title>Template 1</title>
          <body className="main-content temp1-body" suppressHydrationWarning={true}>
            <AuthProvider>
              <Redux>{children}</Redux>
            </AuthProvider>
          </body>
        </html>
      ) : pathName == "/template5" ? (
        <html lang="en" className="temp5-html">
          <title>Template 5</title>
          <body className="temp5-body" suppressHydrationWarning={true}>
            <AuthProvider>
              <Redux>{children}</Redux>
            </AuthProvider>
          </body>
        </html>
      ) : pathName == "/template2" ? (
        <html lang="en" className="temp2-html">
          <title>Template 2</title>
          <body className="temp2-body" suppressHydrationWarning={true}>
            <AuthProvider>
              <Redux>{children}</Redux>
            </AuthProvider>
          </body>
        </html>
      ) : (
        <html lang="en">
        <title>Online Portfolio Generator</title>
          <body className="dark:bg-[#0b1120]" suppressHydrationWarning={true}>
            <Providers>
              <AuthProvider>
                <Redux>{children}</Redux>
              </AuthProvider>
              <ToastifyNotifications />
            </Providers>
          </body>
        </html>
      )}
    </>
  );
}
