"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastifyNotifications from "./components/ToastifyNotifications";
import { AuthProvider } from "./Provider";
import Providers from "./Providers";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();
  return (
    <>
      {pathName !== "/template1" ? (
        <html lang="en">
          <body className="dark:bg-[#0b1120]" suppressHydrationWarning={true}>
            <Providers>
              <AuthProvider>{children}</AuthProvider>
              <ToastifyNotifications />
            </Providers>
          </body>
        </html>
      ) : (
        <html lang="en">
          <body className="main-content body" suppressHydrationWarning={true}>
          <AuthProvider>
            {children}
          </AuthProvider>
          </body>
        </html>
      )}
    </>
  );
}
