import { Inter } from "next/font/google";
import "./globals.css";
import ToastifyNotifications from "./components/ToastifyNotifications";
import { AuthProvider } from "./Provider";
import Providers from './Providers'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-[#0b1120]">
        <Providers>
        <AuthProvider>
        {children}
        </AuthProvider>
        <ToastifyNotifications />
        </Providers>
      </body>
    </html>
  );
}
